/**
 * Builds the self-contained browser ESM artifact at dist/browser/liminal.js.
 *
 * The artifact is a single file: the compiled ESM sources bundled together
 * with the wasm-bindgen glue, plus the protocol WASM binary inlined as base64
 * (esbuild `binary` loader) and registered via `setDefaultWasmSource`. It is
 * offline, deterministic, and addressable from an import map entry pointing at
 * this one file — no bare imports, no CDN references, no runtime fetch.
 *
 * Guarantees enforced here, at build time (the build fails loudly otherwise):
 *  - only the explicitly shimmed `node:` builtin ever resolves; any new
 *    `node:` dependency in the graph is a build error, not a silent break;
 *  - two independent bundle passes produce byte-identical output;
 *  - the emitted artifact contains no static `import`/`export ... from`
 *    statements and no dynamic `import(` calls;
 *  - the emitted artifact embeds the exact WASM binary bytes (base64 prefix
 *    check against wasm/liminal_protocol_wasm_bg.wasm).
 */
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const entryPoint = path.join(packageRoot, "scripts", "browser-entry.mjs");
const wasmBinaryPath = path.join(packageRoot, "wasm", "liminal_protocol_wasm_bg.wasm");
const outputDirectory = path.join(packageRoot, "dist", "browser");
const outputPath = path.join(outputDirectory, "liminal.js");

/**
 * The only Node builtins the bundled graph is allowed to reference, mapped to
 * browser shims. Both current references are dynamic imports behind
 * Node-runtime guards (`src/wasm.ts` file-URL loading, `src/codegen.ts`
 * `generateFromFile`); the shims keep the artifact free of `node:` specifiers
 * and fail loudly if those paths are ever reached in a browser.
 */
const nodeBuiltinShims = new Map([
  [
    "node:fs/promises",
    [
      "const unavailable = (name) => () => {",
      "  throw new Error(",
      "    `the Node fs/promises ${name} function is unavailable in the @ablative/liminal browser artifact`,",
      "  );",
      "};",
      "export const readFile = unavailable(\"readFile\");",
      "export const writeFile = unavailable(\"writeFile\");",
      "export default { readFile, writeFile };",
    ].join("\n"),
  ],
]);

const nodeBuiltinShimPlugin = {
  name: "node-builtin-shim",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^node:/ }, (args) => {
      if (!nodeBuiltinShims.has(args.path)) {
        return {
          errors: [
            {
              text:
                `${args.path} (imported by ${args.importer}) has no browser shim; ` +
                "add one to scripts/build-browser.mjs or remove the dependency",
            },
          ],
        };
      }
      return { path: args.path, namespace: "node-builtin-shim" };
    });
    pluginBuild.onLoad({ filter: /.*/, namespace: "node-builtin-shim" }, (args) => {
      const contents = nodeBuiltinShims.get(args.path);
      if (contents === undefined) {
        return {
          errors: [{ text: `No shim source registered for ${args.path}` }],
        };
      }
      return { contents, loader: "js" };
    });
  },
};

const manifest = JSON.parse(readFileSync(path.join(packageRoot, "package.json"), "utf8"));

async function bundle() {
  const result = await build({
    absWorkingDir: packageRoot,
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    write: false,
    outfile: outputPath,
    loader: { ".wasm": "binary" },
    plugins: [nodeBuiltinShimPlugin],
    legalComments: "none",
    banner: {
      js:
        `// ${manifest.name} ${manifest.version} — self-contained browser ESM artifact.\n` +
        "// Bundled sources + inlined protocol WASM (base64); no imports, no fetch.\n" +
        "// Generated by scripts/build-browser.mjs. Do not edit.",
    },
    logLevel: "silent",
  });
  if (result.errors.length > 0 || result.warnings.length > 0) {
    const messages = [...result.errors, ...result.warnings].map((message) => message.text);
    throw new Error(`esbuild reported problems:\n${messages.join("\n")}`);
  }
  if (result.outputFiles.length !== 1) {
    throw new Error(`Expected exactly one output file, got ${result.outputFiles.length}`);
  }
  return result.outputFiles[0].contents;
}

function assertSelfContained(artifactText) {
  const staticImportPattern = /^\s*(?:import\b|export\s+[^;]*?\bfrom\b)/m;
  const staticMatch = staticImportPattern.exec(artifactText);
  if (staticMatch !== null) {
    throw new Error(`Artifact contains a static module dependency: ${staticMatch[0].trim()}`);
  }
  const dynamicImportPattern = /\bimport\s*\(/;
  const dynamicMatch = dynamicImportPattern.exec(artifactText);
  if (dynamicMatch !== null) {
    throw new Error("Artifact contains a dynamic import() call; it must be fully inlined");
  }
  if (/["'`]node:/.test(artifactText)) {
    throw new Error("Artifact references a node: builtin specifier");
  }
  const wasmBytes = readFileSync(wasmBinaryPath);
  // 510 is divisible by 3, so this base64 prefix is a strict prefix of the
  // full binary's base64 encoding — proving the artifact embeds these bytes.
  const alignedPrefix = wasmBytes.subarray(0, 510).toString("base64");
  if (!artifactText.includes(alignedPrefix)) {
    throw new Error("Artifact does not embed the protocol WASM binary bytes");
  }
}

const firstPass = Buffer.from(await bundle());
const secondPass = Buffer.from(await bundle());
if (!firstPass.equals(secondPass)) {
  throw new Error("Browser artifact build is not deterministic across passes");
}
assertSelfContained(firstPass.toString("utf8"));

mkdirSync(outputDirectory, { recursive: true });
writeFileSync(outputPath, firstPass);
process.stdout.write(
  `browser artifact: ${path.relative(packageRoot, outputPath)} (${firstPass.byteLength} bytes)\n`,
);
